# Generated by Django 4.0 on 2021-12-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soundboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soundboard_name', models.CharField(max_length=500)),
                ('soundboard_image', models.ImageField(upload_to='images/')),
                ('soundboard_description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='SoundboardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Soundboard Category',
                'verbose_name_plural': 'Soundboard Categories',
            },
        ),
        migrations.CreateModel(
            name='SoundCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=500)),
                ('soundboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundboard.soundboard')),
            ],
            options={
                'verbose_name': 'Sound Category',
                'verbose_name_plural': 'Sound Categories',
            },
        ),
        migrations.AddField(
            model_name='soundboard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundboard.soundboardcategory'),
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_name', models.CharField(max_length=500)),
                ('sound_file', models.FileField(upload_to='sounds/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundboard.soundcategory')),
            ],
        ),
    ]
